"""Long-term memory — importance-scored, persistent knowledge store.

Long-term memory holds all project knowledge that should survive phase
transitions and session restarts:

  - Phase syntheses       importance=2.0  (generated by LLM, most valuable)
  - User decisions        importance=1.8  (explicit choices from ask_human)
  - Key findings          importance=1.5  (extracted insights)
  - Step results          importance=1.0  (raw step outputs)

Retrieval combines:
  1. Structural  — by phase and content_type (fast, deterministic)
  2. Keyword     — overlap between query keywords and stored keywords
  3. Importance  — higher-scored items are preferred when budget is tight

All data is stored in the `memory_items` table (the MemoryItem ORM model).
"""

from __future__ import annotations

import re
import uuid
from typing import List, Optional, Tuple

from sqlalchemy import select

from app.models.database import async_session
from app.models.project import MemoryItem

PHASE_ORDER = ["inception", "blueprinting", "coding", "writing"]

# Maximum chars allowed per synthesis item in a planning context window
MAX_SYNTHESIS_CHARS = 900

# Importance scores for standard content types
IMPORTANCE = {
    "synthesis": 2.0,
    "user_decision": 1.8,
    "key_finding": 1.5,
    "conclusion": 1.3,
    "result": 1.0,
    "analysis": 1.0,
    "code": 0.8,
}


class LongTermMemory:
    """Persistent, importance-scored knowledge store.

    All writes go to the `memory_items` table.  The same table is used by
    the legacy ContextStore — LongTermMemory is a superset of that API.
    """

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    async def remember(
        self,
        project_id: str,
        title: str,
        content: str,
        phase: str,
        content_type: str = "result",
        importance: Optional[float] = None,
    ) -> MemoryItem:
        """Persist a memory item with automatic importance scoring.

        If ``importance`` is not provided, it is inferred from
        ``content_type`` using the ``IMPORTANCE`` lookup table.
        """
        if importance is None:
            importance = IMPORTANCE.get(content_type, 1.0)

        keywords = _extract_keywords(content)

        async with async_session() as session:
            item = MemoryItem(
                project_id=uuid.UUID(str(project_id)),
                phase=phase,
                # synthesis items use step_index=9999 to sort last
                step_index=9999 if content_type == "synthesis" else 0,
                step_title=title,
                content=content,
                content_type=content_type,
                keywords=keywords,
                importance=importance,
            )
            session.add(item)
            await session.commit()
            await session.refresh(item)
            return item

    async def remember_step(
        self,
        project_id: str,
        phase: str,
        step_index: int,
        step_title: str,
        content: str,
        content_type: str = "result",
    ) -> MemoryItem:
        """Persist a numbered step result (convenience wrapper)."""
        keywords = _extract_keywords(content)
        importance = IMPORTANCE.get(content_type, 1.0)

        async with async_session() as session:
            item = MemoryItem(
                project_id=uuid.UUID(str(project_id)),
                phase=phase,
                step_index=step_index,
                step_title=step_title,
                content=content,
                content_type=content_type,
                keywords=keywords,
                importance=importance,
            )
            session.add(item)
            await session.commit()
            await session.refresh(item)
            return item

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    async def recall_synthesis(
        self, project_id: str, phase: str
    ) -> Optional[str]:
        """Return the content of the latest synthesis item for a phase."""
        item = await self._get_latest_synthesis(project_id, phase)
        return item.content if item else None

    async def recall_by_phase(
        self, project_id: str, phase: str
    ) -> List[MemoryItem]:
        """Return all non-synthesis items for a phase, sorted by step_index."""
        async with async_session() as session:
            result = await session.execute(
                select(MemoryItem)
                .where(
                    MemoryItem.project_id == uuid.UUID(str(project_id)),
                    MemoryItem.phase == phase,
                    MemoryItem.content_type != "synthesis",
                )
                .order_by(MemoryItem.step_index, MemoryItem.created_at)
            )
            return list(result.scalars().all())

    async def recall_relevant(
        self,
        project_id: str,
        query_keywords: List[str],
        exclude_phase: Optional[str] = None,
        top_k: int = 5,
    ) -> List[MemoryItem]:
        """Retrieve items ranked by keyword overlap × importance.

        Items from the excluded phase (usually the current phase) are
        omitted so we don't return the same phase's work as context.
        """
        async with async_session() as session:
            stmt = select(MemoryItem).where(
                MemoryItem.project_id == uuid.UUID(str(project_id)),
                MemoryItem.content_type != "synthesis",
            )
            if exclude_phase:
                stmt = stmt.where(MemoryItem.phase != exclude_phase)
            result = await session.execute(stmt)
            candidates = list(result.scalars().all())

        if not candidates:
            return []

        scored: list[Tuple[float, MemoryItem]] = []
        query_set = set(kw.lower() for kw in query_keywords)
        for item in candidates:
            item_kws = set(kw.lower() for kw in (item.keywords or []))
            overlap = len(query_set & item_kws)
            score = overlap * item.importance
            scored.append((score, item))

        scored.sort(key=lambda t: t[0], reverse=True)
        return [item for _, item in scored[:top_k] if _ > 0]

    async def build_phase_context(
        self,
        project_id: str,
        current_phase: str,
        max_chars: int = 2000,
    ) -> str:
        """Build context from completed previous phases for plan creation.

        Uses synthesis items when available; falls back to the most recent
        step result for phases that haven't been synthesized yet.
        """
        current_idx = (
            PHASE_ORDER.index(current_phase)
            if current_phase in PHASE_ORDER
            else 0
        )
        parts: list[str] = []
        used = 0

        for prev_phase in PHASE_ORDER[:current_idx]:
            synthesis = await self._get_latest_synthesis(project_id, prev_phase)
            if synthesis:
                snippet = (
                    synthesis.content[:MAX_SYNTHESIS_CHARS]
                    if len(synthesis.content) > MAX_SYNTHESIS_CHARS
                    else synthesis.content
                )
                entry = f"### {prev_phase.title()} 阶段综合\n{snippet}"
            else:
                # Fallback: last step result
                items = await self.recall_by_phase(project_id, prev_phase)
                if not items:
                    continue
                last = items[-1]
                snippet = last.content[:400] if len(last.content) > 400 else last.content
                entry = f"### {prev_phase.title()} 阶段（最后步骤）\n{snippet}"

            if used + len(entry) < max_chars:
                parts.append(entry)
                used += len(entry)

        return "\n\n".join(parts)

    async def build_step_context(
        self,
        project_id: str,
        current_phase: str,
        current_step_index: int,
        max_chars: int = 2000,
    ) -> str:
        """Build long-term context for a step execution.

        Includes previous phase syntheses (up to 60% of budget) then
        earlier steps in the current phase.
        """
        parts: list[str] = []
        used = 0
        budget = max_chars

        # Previous phase syntheses
        current_idx = (
            PHASE_ORDER.index(current_phase)
            if current_phase in PHASE_ORDER
            else 0
        )
        for prev_phase in PHASE_ORDER[:current_idx]:
            synthesis = await self._get_latest_synthesis(project_id, prev_phase)
            if synthesis:
                cap = int(budget * 0.6)
                snippet = synthesis.content[:cap]
                label = f"### 【{prev_phase.title()} 综合】\n{snippet}"
                if used + len(label) < budget:
                    parts.append(label)
                    used += len(label)

        # Earlier steps in current phase (most recent first)
        current_items = await self.recall_by_phase(project_id, current_phase)
        prior = [i for i in current_items if i.step_index < current_step_index]
        for item in reversed(prior):
            snippet = item.content[:500] if len(item.content) > 500 else item.content
            entry = f"**步骤 {item.step_index + 1}：{item.step_title}**\n{snippet}"
            if used + len(entry) < budget:
                parts.append(entry)
                used += len(entry)
            else:
                break

        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _get_latest_synthesis(
        self, project_id: str, phase: str
    ) -> Optional[MemoryItem]:
        async with async_session() as session:
            result = await session.execute(
                select(MemoryItem)
                .where(
                    MemoryItem.project_id == uuid.UUID(str(project_id)),
                    MemoryItem.phase == phase,
                    MemoryItem.content_type == "synthesis",
                )
                .order_by(MemoryItem.created_at.desc())
                .limit(1)
            )
            return result.scalar_one_or_none()


# ---------------------------------------------------------------------------
# Keyword extraction (shared utility)
# ---------------------------------------------------------------------------

def _extract_keywords(text: str, max_keywords: int = 20) -> List[str]:
    """Extract domain-relevant keywords from Chinese/English text."""
    # Strip code blocks
    text = re.sub(r"```[\s\S]*?```", "", text)

    # Domain math-modeling terms (priority)
    domain = re.findall(
        r"(?:优化|模型|算法|预测|评价|分析|结果|数据|方程|矩阵|"
        r"回归|分类|聚类|神经网络|遗传|退火|规划|约束|目标函数|"
        r"灵敏度|验证|仿真|数值|参数|变量|假设|结论|图表|代码)",
        text,
    )
    chinese = re.findall(r"[\u4e00-\u9fff]{2,6}", text)
    english = re.findall(r"[a-zA-Z]{4,}", text.lower())

    seen: set[str] = set()
    unique: list[str] = []
    for kw in domain + chinese[:12] + english[:8]:
        if kw not in seen:
            seen.add(kw)
            unique.append(kw)
            if len(unique) >= max_keywords:
                break
    return unique
